# Generated by Django 4.2.2 on 2023-09-29 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spotify.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(default='album.png', upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='')),
                ('nickname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.ImageField(default='music.png', upload_to='')),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('release_date', models.DateField(auto_now=True)),
                ('music_file', models.FileField(upload_to='', validators=[spotify.validators.validate_is_audio])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ManyToManyField(to='spotify.music')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
    ]
