# Generated by Django 4.2.2 on 2023-10-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
    ]
